CREATE TABLE IF NOT EXISTS PRODUTO (
    codigo VARCHAR(30) PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    valor_padrao DECIMAL(15, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS VENDA_STAGING (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda VARCHAR(50) NOT NULL,
    codigo_cliente VARCHAR(50) NOT NULL,
    codigo_produto VARCHAR(30) NOT NULL,
    quantidade INT NOT NULL,
    valor_unitario DECIMAL(15, 2) NOT NULL,
    valor_total DECIMAL(15, 2) NOT NULL,
    data_venda DATE NOT NULL,
    forma_pagamento VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    data_importacao TIMESTAMP NOT NULL,
    job_execution_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS FATURA (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_staging_id BIGINT NOT NULL,
    id_venda VARCHAR(50) NOT NULL,
    codigo_cliente VARCHAR(50) NOT NULL,
    codigo_produto VARCHAR(30) NOT NULL,
    valor_total DECIMAL(15, 2) NOT NULL,
    data_emissao DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    job_execution_id BIGINT NOT NULL,
    CONSTRAINT UK_FATURA_VENDA UNIQUE (venda_staging_id)
);

CREATE TABLE IF NOT EXISTS REGISTRO_REJEITADO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_execution_id BIGINT NOT NULL,
    step_execution_id BIGINT NOT NULL,
    numero_linha INT,
    id_venda VARCHAR(50),
    motivo_rejeicao VARCHAR(500) NOT NULL,
    conteudo_original VARCHAR(2000),
    data_rejeicao TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS RESUMO_EXECUCAO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_execution_id BIGINT NOT NULL UNIQUE,
    nome_job VARCHAR(120) NOT NULL,
    arquivo_entrada VARCHAR(1000) NOT NULL,
    data_processamento DATE NOT NULL,
    total_lidos INT NOT NULL,
    total_gravados INT NOT NULL,
    total_rejeitados INT NOT NULL,
    total_faturas INT NOT NULL,
    status_final VARCHAR(40) NOT NULL,
    data_inicio TIMESTAMP,
    data_fim TIMESTAMP
);

MERGE INTO PRODUTO (codigo, nome, valor_padrao) KEY (codigo) VALUES
('PROD-001', 'Teclado mecanico', 99.90),
('PROD-002', 'Mouse sem fio', 149.90),
('PROD-003', 'Monitor 24 polegadas', 899.90);
